// Comprehensive Arabic country names mapping
export const arabicCountryNames: Record<string, string> = {
  "Afghanistan": "أفغانستان",
  "Albania": "ألبانيا",
  "Algeria": "الجزائر",
  "Andorra": "أندورا",
  "Angola": "أنغولا",
  "Argentina": "الأرجنتين",
  "Armenia": "أرمينيا",
  "Australia": "أستراليا",
  "Austria": "النمسا",
  "Azerbaijan": "أذربيجان",
  "Bahamas": "البهاما",
  "Bahrain": "البحرين",
  "Bangladesh": "بنغلاديش",
  "Barbados": "بربادوس",
  "Belarus": "بيلاروس",
  "Belgium": "بلجيكا",
  "Belize": "بليز",
  "Benin": "بنين",
  "Bhutan": "بوتان",
  "Bolivia": "بوليفيا",
  "Bosnia and Herzegovina": "البوسنة والهرسك",
  "Botswana": "بوتسوانا",
  "Brazil": "البرازيل",
  "Brunei": "بروناي",
  "Bulgaria": "بلغاريا",
  "Burkina Faso": "بوركينا فاسو",
  "Burundi": "بوروندي",
  "Cambodia": "كمبوديا",
  "Cameroon": "الكاميرون",
  "Canada": "كندا",
  "Cape Verde": "الرأس الأخضر",
  "Central African Republic": "جمهورية أفريقيا الوسطى",
  "Chad": "تشاد",
  "Chile": "تشيلي",
  "China": "الصين",
  "Colombia": "كولومبيا",
  "Comoros": "جزر القمر",
  "Congo": "الكونغو",
  "Costa Rica": "كوستاريكا",
  "Croatia": "كرواتيا",
  "Cuba": "كوبا",
  "Cyprus": "قبرص",
  "Czech Republic": "جمهورية التشيك",
  "Denmark": "الدنمارك",
  "Djibouti": "جيبوتي",
  "Dominica": "دومينيكا",
  "Dominican Republic": "جمهورية الدومينيكان",
  "Ecuador": "الإكوادور",
  "Egypt": "مصر",
  "El Salvador": "السلفادور",
  "Equatorial Guinea": "غينيا الاستوائية",
  "Eritrea": "إريتريا",
  "Estonia": "إستونيا",
  "Ethiopia": "إثيوبيا",
  "Fiji": "فيجي",
  "Finland": "فنلندا",
  "France": "فرنسا",
  "Gabon": "الغابون",
  "Gambia": "غامبيا",
  "Georgia": "جورجيا",
  "Germany": "ألمانيا",
  "Ghana": "غانا",
  "Greece": "اليونان",
  "Grenada": "غرينادا",
  "Guatemala": "غواتيمالا",
  "Guinea": "غينيا",
  "Guinea-Bissau": "غينيا بيساو",
  "Guyana": "غيانا",
  "Haiti": "هايتي",
  "Honduras": "هندوراس",
  "Hungary": "المجر",
  "Iceland": "آيسلندا",
  "India": "الهند",
  "Indonesia": "إندونيسيا",
  "Iran": "إيران",
  "Iraq": "العراق",
  "Ireland": "أيرلندا",
  "Israel": "إسرائيل",
  "Italy": "إيطاليا",
  "Jamaica": "جامايكا",
  "Japan": "اليابان",
  "Jordan": "الأردن",
  "Kazakhstan": "كازاخستان",
  "Kenya": "كينيا",
  "Kiribati": "كيريباتي",
  "Kuwait": "الكويت",
  "Kyrgyzstan": "قيرغيزستان",
  "Laos": "لاوس",
  "Latvia": "لاتفيا",
  "Lebanon": "لبنان",
  "Lesotho": "ليسوتو",
  "Liberia": "ليبيريا",
  "Libya": "ليبيا",
  "Liechtenstein": "ليختنشتاين",
  "Lithuania": "ليتوانيا",
  "Luxembourg": "لوكسمبورغ",
  "Madagascar": "مدغشقر",
  "Malawi": "مالاوي",
  "Malaysia": "ماليزيا",
  "Maldives": "جزر المالديف",
  "Mali": "مالي",
  "Malta": "مالطا",
  "Marshall Islands": "جزر مارشال",
  "Mauritania": "موريتانيا",
  "Mauritius": "موريشيوس",
  "Mexico": "المكسيك",
  "Micronesia": "ميكرونيسيا",
  "Moldova": "مولدوفا",
  "Monaco": "موناكو",
  "Mongolia": "منغوليا",
  "Montenegro": "الجبل الأسود",
  "Morocco": "المغرب",
  "Mozambique": "موزمبيق",
  "Myanmar": "ميانمار",
  "Namibia": "ناميبيا",
  "Nauru": "ناورو",
  "Nepal": "نيبال",
  "Netherlands": "هولندا",
  "New Zealand": "نيوزيلندا",
  "Nicaragua": "نيكاراغوا",
  "Niger": "النيجر",
  "Nigeria": "نيجيريا",
  "North Korea": "كوريا الشمالية",
  "North Macedonia": "مقدونيا الشمالية",
  "Norway": "النرويج",
  "Oman": "عمان",
  "Pakistan": "باكستان",
  "Palau": "بالاو",
  "Palestine": "فلسطين",
  "Panama": "بنما",
  "Papua New Guinea": "بابوا غينيا الجديدة",
  "Paraguay": "باراغواي",
  "Peru": "بيرو",
  "Philippines": "الفلبين",
  "Poland": "بولندا",
  "Portugal": "البرتغال",
  "Qatar": "قطر",
  "Romania": "رومانيا",
  "Russia": "روسيا",
  "Rwanda": "رواندا",
  "Saint Kitts and Nevis": "سانت كيتس ونيفيس",
  "Saint Lucia": "سانت لوسيا",
  "Saint Vincent and the Grenadines": "سانت فنسنت والغرينادين",
  "Samoa": "ساموا",
  "San Marino": "سان مارينو",
  "Sao Tome and Principe": "ساو تومي وبرينسيبي",
  "Saudi Arabia": "السعودية",
  "Senegal": "السنغال",
  "Serbia": "صربيا",
  "Seychelles": "سيشيل",
  "Sierra Leone": "سيراليون",
  "Singapore": "سنغافورة",
  "Slovakia": "سلوفاكيا",
  "Slovenia": "سلوفينيا",
  "Solomon Islands": "جزر سليمان",
  "Somalia": "الصومال",
  "South Africa": "جنوب أفريقيا",
  "South Korea": "كوريا الجنوبية",
  "South Sudan": "جنوب السودان",
  "Spain": "إسبانيا",
  "Sri Lanka": "سريلانكا",
  "Sudan": "السودان",
  "Suriname": "سورينام",
  "Sweden": "السويد",
  "Switzerland": "سويسرا",
  "Syria": "سوريا",
  "Taiwan": "تايوان",
  "Tajikistan": "طاجيكستان",
  "Tanzania": "تنزانيا",
  "Thailand": "تايلاند",
  "Timor-Leste": "تيمور الشرقية",
  "Togo": "توغو",
  "Tonga": "تونغا",
  "Trinidad and Tobago": "ترينيداد وتوباغو",
  "Tunisia": "تونس",
  "Turkey": "تركيا",
  "Turkmenistan": "تركمانستان",
  "Tuvalu": "توفالو",
  "Uganda": "أوغندا",
  "Ukraine": "أوكرانيا",
  "United Arab Emirates": "الإمارات العربية المتحدة",
  "United Kingdom": "المملكة المتحدة",
  "United States": "الولايات المتحدة",
  "Uruguay": "أوروغواي",
  "Uzbekistan": "أوزبكستان",
  "Vanuatu": "فانواتو",
  "Vatican City": "الفاتيكان",
  "Venezuela": "فنزويلا",
  "Vietnam": "فيتنام",
  "Yemen": "اليمن",
  "Zambia": "زامبيا",
  "Zimbabwe": "زيمبابوي",
  // Additional country name variations
  "Ivory Coast": "ساحل العاج",
  "Côte d'Ivoire": "ساحل العاج",
  "Democratic Republic of the Congo": "جمهورية الكونغو الديمقراطية",
  "Republic of the Congo": "جمهورية الكونغو",
  "DR Congo": "جمهورية الكونغو الديمقراطية",
  "Congo, Democratic Republic": "جمهورية الكونغو الديمقراطية",
  "Congo, Republic": "جمهورية الكونغو",
  "São Tomé and Príncipe": "ساو تومي وبرينسيبي",
  "São Tomé & Príncipe": "ساو تومي وبرينسيبي",
};

